### ISSUE TITLE
平台入驻邀请

### ISSUE THREAD

**Issue by specialJC-T** [siam1026/siam-server#2]
hi，我们是一家在线课程平台，支持作者入驻制作课程上线销售，您的这个项目功能十分全面，非常适合学生作为毕设项目学习，所以希望能邀请您入驻平台，投稿相关此项目开发的课程，详细入驻平台介绍，可以 [👉点击这里](https://www.lanqiao.cn/questions/503610/) 了解，期待您的联系～

**Comment by siam1026** [comment]
1
